version: "3"

services:
  cloudc2:
    container_name: cloudc2
    image: sund/cloudc2:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "8080:8080/tcp"
      - "8443:443/tcp"
    environment:
      TZ: 'America/New_York'
    volumes:
      - '~/Local/appdata/cloudc2/:/c2config/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    restart: unless-stopped
